services:
  frontend:
    build:
      context: ./frontend
      args:
        - VUE_APP_API_URL=/api
    ports: ["80:80"]
    networks: ["app-network"]
    depends_on: ["backend"]

  backend:
    build: ./backend
    ports: ["3000:3000"]
    networks: ["app-network"]
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes: ["./backend/storage:/app/storage"]
    user: "node"

networks:
  app-network:
    driver: bridge